server:
  port: 8081

spring:
  application:
    name: course-edge-api

dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: zookeeper://192.168.150.160:2181
    group: local
