spring:
  datasource:
    password: 123456
    username: root
    url: jdbc:mysql://localhost:3306/05spring_mysql_jms_jta
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    property-naming-strategy: SNAKE_CASE
  activemq:
    broker-url: tcp://localhost:61616
